### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Nagefire**
Changed the instructions for "git" from cloning the old repository under @jurobystricky (which no longer compiles) to this branch under @kaduke

### CODE REVIEW

**Comment by Joseph-Smith** [comment]
The clone instructions require further clarification because the head branch will not compile on 4.15 or greater,  so people need to choose the correct branch for their kernel version unless the port-to-4.15 branch is promoted to head and I don't know if that branch has been tested on older kernels.

**Comment by Joseph-Smith** [comment]
The clone instructions require further clarification about which branch to choose and how to format the URL for a branch, unless the head compiles on all kernels, but I don't think it does. I think you have to use the port-to-4.15 branch for it to compile on 4.15 or newer.

**Comment by Nagefire** [comment]
To update kernel testing, I've compiled the branch under @kaduke and it functions for kernel >= 4.15 for  ARMv7 and x86_64, and it appears that this repo compiles for all kernels < 4.15, I propose that we fork in the edited files from [this](https://github.com/kaduke/Netgear-A6210/commit/654ce59d1babed82f41a7f380a125ef7421d8541) commit and then create an install script that substitutes in this version of rt_linux.h for kernels >= 4.15 while keeping the other files for older kernels

We wouldn't need to update the README.md at all, but rather create a simple install script.

**Comment by Joseph-Smith** [comment]
Which branch? There are 4 or 5 I think.

**Comment by Nagefire** [comment]
The one here:
https://github.com/kaduke/Netgear-A6210
This commit fixes the issue with the newer kernel versions:
https://github.com/kaduke/Netgear-A6210/commit/654ce59d1babed82f41a7f380a125ef7421d8541

**Comment by Nagefire** [comment]
I tried building all of the forks of this repo and this was the only one that worked

**Comment by Joseph-Smith** [comment]
I meant which branch within this fork. At one point I thought I tried the master and it didn't work then I tried a branch within this fork and it did work. But that was a long time ago and this comment is more to document what I meant. You can see all the branches within a fork by going here:   

https://github.com/kaduke/Netgear-A6210/branches

I have tested up to 4.18.16 Fedora and the driver works to there. I will test 4.19 when it comes out for Fedora 29.

**Pull request merged**
